😪

diff --git a/.github/workflows/test-build.yml b/.github/workflows/test-build.yml
--- a/.github/workflows/test-build.yml
+++ b/.github/workflows/test-build.yml
@@ -101,7 +101,10 @@ jobs:
           repository: hay-espacio-en-el-taco/dbs-scraper
       - name: Confirm that downloaded files are correct
         run: |
-          if [ ! -f dowloaded_cards.json ] || [ ! $(wc -c < dowloaded_cards.json) -ge 50000 ]; then exit 1; fi
+          if [ ! -f dowloaded_cards.json ] || [ ! $(wc -c < dowloaded_cards.json) -ge 50000 ]; then
+              echo 'Failed!';
+              exit 1;
+          fi
 
       - name: It should delete release with tag Test 
         uses: ./ # Uses the action in the root directory
